# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.9.2"

package:
  name: types-aiobotocore-logs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-aiobotocore-logs/types_aiobotocore_logs-${{ version }}.tar.gz
  sha256: b4e0fbd4f9ae08da2265d3e4e38666f5115f7d5cfe0933b4556205f09302d956

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - aiobotocore
    - typing_extensions

tests:
  - python:
      imports:
        - types_aiobotocore_logs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/youtype/mypy_boto3_builder
  summary: Type annotations for aiobotocore.CloudWatchLogs ${{ version }} service generated with mypy-boto3-builder
  license: MIT
  license_file: LICENSE
  documentation: https://youtype.github.io/types_aiobotocore_docs/
  repository: https://github.com/youtype/mypy_boto3_builder

extra:
  recipe-maintainers:
    - vemel
    - fhoehle
